name: Java CI with Gradle

on:
  push:
    branches: [ "add-pipeline-jar" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Nexus Repository Publisher for GitHub Actions
        uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          serverUrl: https://nexus-ynov-sandbox.asys-cloud.fr/repository/maven-releases/
          username: jenkins
          password: hDkxFxBSwmQ3ANLBFt
          format: maven2
          repository: maven-releases
          coordinates: groupId=com.example artifactId=app version=1.0.0
          assets: extension=jar
          filename: ./build/libs/ynov-eval-core-api-java.jar
